"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x*)s&zioxu2*82et&##*jb#xd5ok)zet*(u4!exl@zx)pmeze%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'coreapi',
    'jazzmin'
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_URL = '/static/'
# Thêm dòng này vào ngay dưới
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ====================================
# JAZZMIN CONFIGURATION (EduCare Link)
# ====================================

JAZZMIN_SETTINGS = {
    # Tiêu đề trên tab trình duyệt
    "site_title": "EduCare Admin",
    "site_header": "EduCare Link",
    "site_brand": "EduCare Quản trị",
    "welcome_sign": "Chào mừng quản trị viên EduCare",
    "copyright": "EduCare Link Ltd",
    
    # Menu bên trái
    "search_model": ["auth.User", "coreapi.Booking"], # Cho phép tìm kiếm nhanh User và Booking
    "topmenu_links": [
        {"name": "Trang chủ App", "url": "home", "permissions": ["auth.view_user"]},
    ],
    
    # Cấu trúc Menu
    "order_with_respect_to": ["coreapi", "auth"], # Ưu tiên hiển thị App coreapi trước
    
    # Icon cho các bảng (Dùng FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "coreapi.Booking": "fas fa-calendar-check",
        "coreapi.CarePartner": "fas fa-user-nurse",
        "coreapi.ParentProfile": "fas fa-user-tie",
        "coreapi.Child": "fas fa-baby",
        "coreapi.Service": "fas fa-list",
        "coreapi.Review": "fas fa-star",
        "coreapi.ChatSession": "fas fa-comments",
    },
}

# Tùy chỉnh giao diện (Màu sắc)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",  # Màu xanh lá cho logo
    "accent": "accent-success",        # Màu điểm nhấn xanh lá
    "navbar": "navbar-success navbar-dark", # Thanh menu trên cùng màu xanh
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,             # Menu trái cố định
    "sidebar": "sidebar-light-success", # Menu trái màu sáng, highlight xanh
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "main_bg_color": None,
    "button_classes": {
        "primary": "btn-success",      # Nút bấm chính màu xanh
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}