# Generated by Django 6.0.1 on 2026-02-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dia_chi',
            field=models.CharField(default='Chưa có địa chỉ', max_length=255),
            preserve_default=False,
        ),
    ]
